---
- name: Send notification message via Slack
  hosts: localhost
  tasks:
    - name: Run Report python script
      script: ./ZendeskReport.py {{ customerSearch }} {{ bearerToken }}
      register: zendeskReport
    - debug: var=zendeskReport.stdout_lines

    - name: Post to Slack
      slack:
        token: T31GN34R3/BGS668SEL/lFuQQDJvNp1xUAipdHh74sHI
        msg: var=zendeskReport.stdout_lines
        icon_emoji: ":zap:"
        username: 'ZendeskReporter'
